---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: alloy-config
  namespace: observability-system
spec:
  interval: 10m
  prune: true
  wait: true
  targetNamespace: observability-system

  path: ./apps/observability-system/alloy/config
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system

  dependsOn:
    - name: alloy
    - name: alertmanager
    - name: mimir
    - name: kube-state-metrics
