---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: pihole-config
  namespace: dns
spec:
  interval: 10m
  prune: true
  wait: true
  targetNamespace: dns

  path: ./apps/dns/pihole/config
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system

  dependsOn:
    - name: pihole
    - name: bitwarden-sdk-server-config
      namespace: security-system
