---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: reloader
  namespace: kube-system
  labels:
    app.kubernetes.io/name: reloader
    app.kubernetes.io/part-of: kube-system
    app.kubernetes.io/managed-by: flux
spec:
  interval: 15m
  url: oci://ghcr.io/stakater/charts/reloader
  ref:
    tag: 2.2.12
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
