---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
  namespace: network-system
  labels:
    app.kubernetes.io/name: external-dns
    app.kubernetes.io/part-of: external-dns
    app.kubernetes.io/managed-by: flux
spec:
  interval: 10m
  chartRef:
    kind: OCIRepository
    name: external-dns

  values:
    fullnameOverride: external-dns

    logLevel: info
    logFormat: text

    interval: 1m
    triggerLoopOnEvent: true

    policy: sync
    txtOwnerId: homelab

    sources:
      - service
      - gateway-httproute
      - crd

    managedRecordTypes: [A]

    domainFilters:
      - reli.cc

    provider:
      name: cloudflare

    extraArgs:
      - --cloudflare-dns-records-per-page=1000
      - --crd-source-apiversion=externaldns.k8s.io/v1alpha1
      - --crd-source-kind=DNSEndpoint

    podAnnotations:
      reloader.stakater.com/auto: "true"

    env:
      - name: CF_API_TOKEN
        valueFrom:
          secretKeyRef:
            name: cloudflare-token-secret
            key: cloudflare-token
