---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bazarr-secret
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore

  target:
    name: bazarr-secret
    creationPolicy: Owner

  data:
    - secretKey: api_key
      remoteRef:
        key: Bazarr API Key
