---
# yaml-language-server: $schema=https://k8s-schemas.mirceanton.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minecraft-server
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore

  target:
    name: minecraft-server
    creationPolicy: Owner

  data:
    - secretKey: RCON_PASSWORD
      remoteRef:
        key: Minecraft Server Password
