---
directory: /music
library: /config/library.db

import:
  copy: no
  move: no
  link: no
  hardlink: no
  autotag: yes
  quiet: yes
  quiet_fallback: skip
  resume: no
  incremental: yes
  timid: no
  write: yes

plugins: musicbrainz fetchart embedart

match:
  preferred:
    media:
      - Digital Media
      - CD
    original_year: yes

art_filename: cover

fetchart:
  auto: yes
  enforce_ratio: 0.5%
  cover_names: cover front art album folder
  high_resolution: yes
  sources:
    - itunes
    - coverart
    - amazon
    - albumart
    - filesystem

embedart:
  auto: yes
  maxwidth: 1000
  ifempty: no
