---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json

apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: mimir
  namespace: observability-system
spec:
  interval: 15m
  url: oci://ghcr.io/grafana/helm-charts/mimir-distributed
  ref:
    tag: 6.1.0
