---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: garage-mimir-key
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore

  target:
    name: garage-mimir-key
    creationPolicy: Owner

  data:
    - secretKey: keyId
      remoteRef:
        key: Garage Mimir Key ID
    - secretKey: secretKey
      remoteRef:
        key: Garage Mimir Secret Key
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: garage-loki-key
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore

  target:
    name: garage-loki-key
    creationPolicy: Owner

  data:
    - secretKey: keyId
      remoteRef:
        key: Garage Loki Key ID
    - secretKey: secretKey
      remoteRef:
        key: Garage Loki Secret Key
