---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json

apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
spec:
  interval: 10m
  chartRef:
    kind: OCIRepository
    name: longhorn

  values:
    defaultSettings:
      defaultDataPath: /var/lib/longhorn-nvme

    global:
      nodeSelector:
        node-role.kubernetes.io/worker: worker

    persistence:
      defaultClass: true

    preUpgradeChecker:
      jobEnabled: false
