---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &secret democratic-csi-secret
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore

  target:
    name: *secret
    creationPolicy: Owner

  data:
    - secretKey: truenas-api-key
      remoteRef:
        key: TrueNAS API Key
