---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-token-secret
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: bitwarden # which vault to use
    kind: ClusterSecretStore

  target:
    name: cloudflare-token-secret # the name of the secret to create
    creationPolicy: Owner

  data:
    - secretKey: cloudflare-token # the key of the secret to create
      remoteRef:
        key: Cloudflare API Token
        property: password
