---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: bitwarden-sdk-server-config
spec:
  interval: 10m
  prune: true
  wait: true
  targetNamespace: security-system

  path: ./apps/security-system/bitwarden-sdk-server/config
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system

  decryption:
    provider: sops

  dependsOn:
    - name: external-secrets-operator
