---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prowlarr
  namespace: media
  labels:
    app.kubernetes.io/name: prowlarr
    app.kubernetes.io/part-of: media-stack
    app.kubernetes.io/managed-by: flux
spec:
  interval: 30m
  timeout: 10m
  chartRef:
    kind: OCIRepository
    name: prowlarr

  values:
    global:
      createDefaultServiceAccount: false

    defaultPodOptions:
      automountServiceAccountToken: false

    controllers:
      prowlarr:
        replicas: 1
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          securityContext:
            fsGroup: 568
            fsGroupChangePolicy: OnRootMismatch
            runAsGroup: 568
            runAsNonRoot: true
            runAsUser: 568
        containers:
          app:
            image:
              repository: ghcr.io/home-operations/prowlarr
              tag: 2.6.3.5592
            env:
              PROWLARR__APP__INSTANCENAME: Prowlarr
              PROWLARR__AUTH__APIKEY:
                valueFrom:
                  secretKeyRef:
                    name: prowlarr-secret
                    key: api_key
              PROWLARR__AUTH__METHOD: External
              PROWLARR__LOG__DBENABLED: "False"
              PROWLARR__LOG__LEVEL: info
              PROWLARR__SERVER__PORT: &port 9696
              PROWLARR__SERVER__ALLOWEDHOSTS: prowlarr.internal.reli.cc,prowlarr.media.svc.cluster.local,prowlarr
              PROWLARR__UPDATE__BRANCH: develop
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /ping
                    port: *port
                    httpHeaders:
                      - name: Host
                        value: localhost
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            resources:
              requests:
                cpu: 20m
                memory: 128Mi
              limits:
                memory: 512Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop: ["ALL"]

    service:
      app:
        ports:
          http:
            port: *port

    persistence:
      config:
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 2Gi
        globalMounts:
          - path: /config
      tmp:
        type: emptyDir
