---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json

apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minio
  namespace: storage-system
  labels:
    app.kubernetes.io/name: minio
    app.kubernetes.io/part-of: minio
    app.kubernetes.io/managed-by: flux
spec:
  interval: 10m
  chartRef:
    kind: OCIRepository
    name: minio

  valuesFrom:
    - kind: Secret
      name: minio-credentials
      valuesKey: root-user
      targetPath: auth.rootUser
    - kind: Secret
      name: minio-credentials
      valuesKey: root-password
      targetPath: auth.rootPassword

  values:
    fullnameOverride: minio

    mode: standalone

    persistence:
      enabled: true
      storageClass: longhorn
      size: 20Gi

    service:
      type: ClusterIP

    ingress:
      enabled: false

    consoleIngress:
      enabled: false
