---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: blackbox-exporter-config
  namespace: observability-system
spec:
  interval: 10m
  prune: true
  wait: true
  targetNamespace: observability-system

  path: ./apps/observability-system/blackbox-exporter/config
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system

  dependsOn:
    - name: blackbox-exporter
    - name: alertmanager
