---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: slskd-secret
  labels:
    app.kubernetes.io/name: slskd
    app.kubernetes.io/part-of: media-stack
    app.kubernetes.io/managed-by: flux
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore

  target:
    name: slskd-secret
    creationPolicy: Owner

  data:
    - secretKey: soulseek_username
      remoteRef:
        key: Soulseek Username
    - secretKey: soulseek_password
      remoteRef:
        key: Soulseek Password
    - secretKey: web_username
      remoteRef:
        key: Slskd Web Username
    - secretKey: web_password
      remoteRef:
        key: Slskd Web Password
    - secretKey: api_key
      remoteRef:
        key: Slskd API Key
