---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/grafana.integreatly.org/grafanafolder_v1beta1.json
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaFolder
metadata:
  name: observability-system
  labels:
    app.kubernetes.io/name: observability-system
    app.kubernetes.io/managed-by: flux
spec:
  title: observability-system
  allowCrossNamespaceImport: true
  instanceSelector:
    matchLabels:
      grafana.internal/instance: grafana
