---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: twingate-secret
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore

  target:
    name: twingate-secret
    creationPolicy: Owner

  data:
    - secretKey: TWINGATE_ACCESS_TOKEN
      remoteRef:
        key: Twingate Access Token
    - secretKey: TWINGATE_REFRESH_TOKEN
      remoteRef:
        key: Twingate Refresh Token
