---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: bazarr
  namespace: media
  labels:
    app.kubernetes.io/name: bazarr
    app.kubernetes.io/part-of: media-stack
    app.kubernetes.io/managed-by: flux
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: bazarr-chart

  values:
    global:
      createDefaultServiceAccount: false

    defaultPodOptions:
      automountServiceAccountToken: false

    controllers:
      bazarr:
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          securityContext:
            fsGroup: 568
            fsGroupChangePolicy: OnRootMismatch
            runAsGroup: 568
            runAsNonRoot: true
            runAsUser: 568
        containers:
          app:
            image:
              repository: ghcr.io/home-operations/bazarr
              tag: 1.5.6
            probes:
              liveness:
                enabled: true
                spec:
                  periodSeconds: 30
                  timeoutSeconds: 5
                  failureThreshold: 5
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: &port 6767
                  periodSeconds: 10
                  timeoutSeconds: 5
                  failureThreshold: 5
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 10
            resources:
              requests:
                cpu: 20m
                memory: 128Mi
              limits:
                memory: 512Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop: ["ALL"]

    service:
      app:
        ports:
          http:
            port: *port

    persistence:
      config:
        existingClaim: bazarr-config
        globalMounts:
          - path: /config
      data:
        existingClaim: media-data
        globalMounts:
          - path: /data
      tmp:
        type: emptyDir
