---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json

apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: alloy
spec:
  interval: 15m
  url: oci://ghcr.io/grafana/helm-charts/alloy
  ref:
    tag: 1.10.0
