apiVersion: v1
kind: Secret
metadata:
    name: bitwarden-access-token
    labels:
        app.kubernetes.io/name: bitwarden-sdk-server
        app.kubernetes.io/part-of: bitwarden-sdk-server
        app.kubernetes.io/managed-by: flux
stringData:
    token: ENC[AES256_GCM,data:Rb06DS8xzZ/nkHzqe9I6KjkJ0DF+cQKVmZ38TECjUlb4PsOgtKwgmPh4xpgsxCfRjenECQBFvJAUfIenrb0ZwW7Om0qtv6iiuDItgLlkI093lYsZP1dhh3VIf+C+WA==,iv:VpetsW1wvT7KKGgPsPxJESi/kSQFPqV0cj/b5hOSRwg=,tag:cjYPFcKwGp2KabNl7n7RbQ==,type:str]
sops:
    age:
        - recipient: age1mffm0ee3uxfp9jzc8u3lq0mgvs5lm8e4dp7gdkkm772syyjcwgqq9xwnrp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4V2JSclEya0hvQVBlRXlv
            emZnQ1VjQ1FaVmVoeDdRem81c1E1VVdBNVc0CllpMDlkeTk4cTl4c3MwOGF1RmQx
            ekZmazlZYnFTbit2RFhOVkN3WDJRbUEKLS0tIHhUYUFQTmpBMGEvOURHMkcyNk5B
            NXJSRUdsQnRVWHh2WnlNTmczMXpndEEK4lWJyM5rvGUj74+JOw3iaS+vJnJLeRow
            bFyt6T+1858IQn0xyjb7pMDIo76Ng08zj0McsQv8N6sBkwZx7Rq6lA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-13T18:16:36Z"
    mac: ENC[AES256_GCM,data:ox0XszwWZELrs/PypNyIdDneH8pcJav8fkIxsv7B5WsG12yECYy5xpn4+3qGHSl0IE4BUInkc8HcVhPnZsFpHoawQlll4Wch9xprWt9J6LpXu04lYffakaZoce4mLvxgLrCyeH0me8h8IwuWtKCzejsjtCSXn58ei7N5uKzOA6s=,iv:dSuSFWXDGdBezq1pYSlkNIY9w76NlqDHofqmmwpnEw8=,tag:5CDp3ksnINgwk6uLWgPw4Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
