---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/clustersecretstore_v1.json
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: bitwarden
  labels:
    app.kubernetes.io/name: bitwarden-sdk-server
    app.kubernetes.io/part-of: bitwarden-sdk-server
    app.kubernetes.io/managed-by: flux
spec:
  provider:
    bitwardensecretsmanager:
      apiURL: https://api.bitwarden.com
      identityURL: https://identity.bitwarden.com
      bitwardenServerSDKURL: https://bitwarden-sdk-server.security-system.svc.cluster.local:9998
      organizationID: "20a9faf3-0af2-423a-9439-b42b002fd2e6"
      projectID: "83f230ab-24e1-4901-b6d8-b42b0031319c"
      caProvider:
        type: Secret
        name: bitwarden-tls-certs
        key: ca.crt
        namespace: security-system
      auth:
        secretRef:
          credentials:
            name: bitwarden-access-token
            key: token
            namespace: security-system
