---
apiVersion: collectors.grafana.com/v1alpha1
kind: Alloy
metadata:
  name: alloy-metrics
  labels:
    app.kubernetes.io/name: alloy
    app.kubernetes.io/part-of: alloy
    app.kubernetes.io/managed-by: flux
spec:
  alloy:
    configMap:
      create: false
      name: alloy-metrics-config
      key: config.alloy
    resources:
      requests:
        cpu: 20m
        memory: 640Mi
      limits:
        memory: 900Mi
    mounts:
      extra:
        - name: proc
          mountPath: /host/proc
          readOnly: true
        - name: sys
          mountPath: /host/sys
          readOnly: true
        - name: udev
          mountPath: /run/udev/data
          readOnly: true

  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "12345"
    prometheus.io/path: "/metrics"

  controller:
    type: daemonset
    hostPID: true
    hostNetwork: true
    dnsPolicy: ClusterFirstWithHostNet
    volumes:
      extra:
        - name: proc
          hostPath:
            path: /proc
        - name: sys
          hostPath:
            path: /sys
        - name: udev
          hostPath:
            path: /run/udev/data

  rbac:
    create: true

  serviceAccount:
    create: true
    name: alloy-metrics
