---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - alloy-metrics-config.yaml
  - alloy.yaml
  - alloy-rules-config.yaml
  - alloy-rules.yaml
  - alloy-rules-rbac.yaml
  - http-route.yaml
