---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json

apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: alertmanager-credentials
  labels:
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/part-of: alertmanager
    app.kubernetes.io/managed-by: flux
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore

  target:
    name: alertmanager-credentials
    creationPolicy: Owner

  data:
    - secretKey: webhookUrl
      remoteRef:
        key: Alertmanager Webhook URL
