---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudnative-pg
  namespace: database-system
  labels:
    app.kubernetes.io/name: cloudnative-pg
    app.kubernetes.io/part-of: database-system
    app.kubernetes.io/managed-by: flux
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: cloudnative-pg

  values:
    fullnameOverride: cloudnative-pg-operator

    replicaCount: 1

    resources:
      requests:
        cpu: 10m
        memory: 256Mi
      limits:
        memory: 512Mi
