---
apiVersion: v1
kind: ConfigMap
metadata:
  name: unbound-custom-conf
  labels:
    app.kubernetes.io/name: unbound
    app.kubernetes.io/part-of: unbound
    app.kubernetes.io/managed-by: flux
data:
  hardening.conf: |
    # https://unbound.docs.nlnetlabs.nl/en/latest/manpages/unbound.conf.html
    server:
        # Don't reveal the resolver's identity/version to clients
        hide-identity: yes
        hide-version: yes
