helmDefaults:
  wait: true
  timeout: 600

repositories:
  - name: longhorn
    url: https://charts.longhorn.io
  - name: metallb
    url: https://metallb.github.io/metallb
  - name: mojo2600
    url: https://mojo2600.github.io/pihole-kubernetes/
  - name: external-dns
    url: https://kubernetes-sigs.github.io/external-dns/

templates:
  default: &default
    createNamespace: true
    missingFileHandler: Warn
    values:
      - values/{{ .Release.Name }}.values.yaml

releases:
  - name: longhorn
    namespace: longhorn-system
    chart: longhorn/longhorn
    version: 1.11.1
    inherit:
      - template: default

  - name: metallb
    namespace: metallb-system
    chart: metallb/metallb
    version: 0.15.3
    inherit:
      - template: default

  - name: pihole
    namespace: pihole
    chart: mojo2600/pihole
    version: 2.35.0
    inherit:
      - template: default

  - name: external-dns
    namespace: external-dns
    chart: external-dns/external-dns
    version: 1.20.0
    inherit:
      - template: default
