---
apiVersion: v1
kind: Namespace
metadata:
  name: dns-system
  labels:
    app.kubernetes.io/name: dns-system
    app.kubernetes.io/managed-by: flux
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
