---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: immich-config
  namespace: media
spec:
  interval: 10m
  prune: true
  wait: true
  targetNamespace: media

  path: ./apps/media/immich/config
  components:
    - ../../../../components/cnpg/
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system

  postBuild:
    substitute:
      APP: immich
      CNPG_IMAGE: ghcr.io/cloudnative-pg/postgresql:18.6-system-bookworm
      CNPG_DATA_STORAGE_SIZE: 10Gi
      CNPG_WAL_STORAGE_SIZE: 2Gi
      CNPG_MEMORY_REQUEST: 512Mi
      CNPG_MEMORY_LIMIT: 1Gi

  dependsOn:
    - name: democratic-csi
      namespace: storage-system
    - name: cloudnative-pg
      namespace: database-system
