---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json

apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: garage
  namespace: storage-system
  labels:
    app.kubernetes.io/name: garage
    app.kubernetes.io/part-of: garage
    app.kubernetes.io/managed-by: flux
spec:
  interval: 10m
  timeout: 15m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  chart:
    spec:
      chart: garage
      version: 0.7.0
      sourceRef:
        kind: HelmRepository
        name: garage
        namespace: storage-system

  values:
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        memory: 512Mi

    garage:
      replicationFactor: "3"
      s3:
        api:
          region: "garage"

    persistence:
      meta:
        storageClass: longhorn
        size: 256Mi
      data:
        storageClass: longhorn
        size: 30Gi

    webui:
      enabled: true
      resources:
        requests:
          cpu: 5m
          memory: 8Mi
        limits:
          memory: 32Mi

    clusterConfig:
      enabled: true
      layout:
        enabled: true
        zone: homelab
      buckets:
        - name: mimir
        - name: loki
      keys:
        mimir-key:
          secretName: garage-mimir-key
          keyId: keyId
          secretKey: secretKey
          buckets:
            - name: mimir
              read: true
              write: true
              owner: true
        loki-key:
          secretName: garage-loki-key
          keyId: keyId
          secretKey: secretKey
          buckets:
            - name: loki
              read: true
              write: true
              owner: true
